/**
 * The built-in document skills (docx / xlsx / pptx / pdf) and the helper scripts they point at.
 *
 * The skill text is what the model acts on, and it names scripts by path through the `{{SKILLS_DIR}}`
 * placeholder. A path that does not exist in resources/skills is a recipe that fails at the moment a user
 * needs it — so every referenced script is checked here, along with the frontmatter the catalog parser
 * relies on and the host-folder resolution the sandbox bind and the IPC share.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import { GUEST_SKILLS_DIR, resolveSkillsHostDir, skillsHostDirExists } from "../electron/tools/builtinSkills.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const skillsMd = path.join(root, "src", "skills", "builtin");
const scriptsDir = path.join(root, "resources", "skills");
const SKILLS = ["docx", "xlsx", "pptx", "pdf"];

/**
 * Byte-compile Python files WITHOUT writing `__pycache__` next to the sources.
 *
 * `python -m py_compile` drops its output beside each input, which quietly dirties the working tree on every test
 * run — and did worse than that here: fourteen `.pyc` files generated by an earlier run were committed, and since
 * `resources/skills` ships via electron-builder's extraResources they would have gone out to every user. Compiling
 * to a temp file removes the cause rather than cleaning up after it.
 */
function compilePython(files) {
  const script = [
    "import py_compile, sys, tempfile, os",
    "tmp = tempfile.mkdtemp()",
    "for i, f in enumerate(sys.argv[1:]):",
    "    py_compile.compile(f, cfile=os.path.join(tmp, f'{i}.pyc'), doraise=True)",
  ].join("\n");
  return spawnSync("python3", ["-c", script, ...files], { encoding: "utf8" });
}

function frontmatter(raw) {
  const m = /^\s*---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw);
  assert.ok(m, "frontmatter block present");
  const data = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(line);
    if (kv) data[kv[1]] = kv[2].trim();
  }
  return { data, body: raw.slice(m[0].length) };
}

test("host folder: packaged under resourcesPath, dev under the repo", () => {
  assert.equal(
    resolveSkillsHostDir({ isPackaged: true, resourcesPath: "/app/resources", appPath: "/app/resources/app.asar" }),
    path.join("/app/resources", "skills"),
  );
  assert.equal(
    resolveSkillsHostDir({ isPackaged: false, appPath: "/repo" }),
    path.join("/repo", "resources", "skills"),
  );
  assert.equal(GUEST_SKILLS_DIR, "/mnt/skills");
  assert.ok(skillsHostDirExists(scriptsDir), "resources/skills exists in the repo");
  assert.equal(skillsHostDirExists(path.join(root, "no-such-folder")), false);
});

test("every built-in skill has the frontmatter the catalog needs and uses the placeholder", () => {
  for (const id of SKILLS) {
    const raw = fs.readFileSync(path.join(skillsMd, `${id}.md`), "utf8");
    const { data, body } = frontmatter(raw);
    assert.equal(data.id, id, `${id}: id matches the file name`);
    assert.ok(data.name, `${id}: name`);
    assert.ok(data.description && data.description.length > 80, `${id}: a trigger-rich description`);
    assert.ok(body.includes("{{SKILLS_DIR}}"), `${id}: refers to its helper scripts through the placeholder`);
    assert.ok(!/\/mnt\/skills|resources\/skills/.test(body), `${id}: never hard-codes a scripts path`);
  }
});

test("every script a skill refers to ships in resources/skills", () => {
  const missing = [];
  for (const id of SKILLS) {
    const raw = fs.readFileSync(path.join(skillsMd, `${id}.md`), "utf8");
    for (const m of raw.matchAll(/\{\{SKILLS_DIR\}\}\/([\w./-]+\.py)/g)) {
      if (!fs.existsSync(path.join(scriptsDir, m[1]))) missing.push(`${id}.md → ${m[1]}`);
    }
  }
  assert.deepEqual(missing, []);
});

test("the helper scripts are valid Python (skipped when python3 is absent)", (t) => {
  const probe = spawnSync("python3", ["--version"], { encoding: "utf8" });
  if (probe.error || probe.status !== 0) return t.skip("python3 not available");
  const files = [];
  const walk = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith(".py")) files.push(p);
    }
  };
  walk(scriptsDir);
  assert.ok(files.length >= 10, `found ${files.length} scripts`);
  const r = compilePython(files);
  assert.equal(r.status, 0, r.stderr);
});

test("packaging stages the folder next to the other resources", () => {
  const yml = fs.readFileSync(path.join(root, "electron-builder.yml"), "utf8");
  assert.match(yml, /from: resources\/skills\n\s+to: skills/);
});

// ── The shared design system ────────────────────────────────────────────────────────────────────
//
// The four skills produce documents a person will look at, and what separates "considered" from
// "generated" is a small set of choices that must be identical across all four: one type scale, one
// palette, one spacing rule. They live in resources/skills/office/theme.py so a model does not have to
// remember hex codes and so a report and the deck summarising it look related.
//
// Contrast is asserted rather than eyeballed: a palette edit that quietly drops a pairing below WCAG AA
// produces a document that is still "on brand" and no longer readable, which nothing else here would catch.

/** Relative luminance of a #RRGGBB string, per WCAG 2.1. */
function luminance(hex) {
  const ch = [0, 2, 4].map((i) => {
    const v = parseInt(hex.slice(i, i + 2), 16) / 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2];
}

function contrast(a, b) {
  const [x, y] = [luminance(a), luminance(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
}

/** Read a `NAME = "HEX"` constant out of theme.py, so the test asserts the shipped values. */
function token(src, name) {
  const m = new RegExp(`^${name} = "([0-9A-Fa-f]{6})"`, "m").exec(src);
  assert.ok(m, `${name} is defined in theme.py`);
  return m[1];
}

test("the design system ships and compiles", (t) => {
  const themePath = path.join(scriptsDir, "office", "theme.py");
  assert.ok(fs.existsSync(themePath), "resources/skills/office/theme.py");
  const probe = spawnSync("python3", ["--version"], { encoding: "utf8" });
  if (probe.error || probe.status !== 0) return t.skip("python3 not available");
  const r = compilePython([themePath]);
  assert.equal(r.status, 0, r.stderr);
});

test("every text/ground pairing the system uses meets WCAG AA", () => {
  const src = fs.readFileSync(path.join(scriptsDir, "office", "theme.py"), "utf8");
  const T = Object.fromEntries(
    ["INK", "BODY", "MUTED", "PAPER", "TINT", "ACCENT", "ACCENT_TINT", "ACCENT_INK", "POSITIVE", "NEGATIVE", "WARNING"]
      .map((n) => [n, token(src, n)]),
  );
  // 4.5:1 is AA for body text; 3:1 is AA for large text (headings) and for UI boundaries.
  const pairs = [
    ["BODY", "PAPER", 4.5, "running text on paper"],
    ["INK", "PAPER", 4.5, "headings on paper"],
    ["MUTED", "PAPER", 4.5, "captions and axis labels on paper"],
    ["INK", "ACCENT_TINT", 4.5, "a table header's text on its fill"],
    ["INK", "TINT", 4.5, "text in a callout or a banded row"],
    ["ACCENT_INK", "PAPER", 4.5, "the accent used as text"],
    ["PAPER", "ACCENT", 4.5, "reversed text on the accent (the Excel header row)"],
    ["NEGATIVE", "PAPER", 4.5, "a negative number"],
    ["POSITIVE", "PAPER", 4.5, "a positive number"],
    ["WARNING", "PAPER", 4.5, "a warning value"],
    ["ACCENT", "PAPER", 3, "the accent as a rule or a chart bar"],
  ];
  for (const [fg, bg, min, what] of pairs) {
    const ratio = contrast(T[fg], T[bg]);
    assert.ok(ratio >= min, `${what}: ${fg} on ${bg} is ${ratio.toFixed(2)}:1, below ${min}:1`);
  }
});

test("the accent is not the Office default, which is the tell of an unstyled document", () => {
  const src = fs.readFileSync(path.join(scriptsDir, "office", "theme.py"), "utf8");
  const accent = token(src, "ACCENT").toUpperCase();
  for (const stock of ["4472C4", "1F4E78", "D9E2F3", "0070C0", "5B9BD5"]) {
    assert.notEqual(accent, stock, "the stock Office blues are what a document looks like when nobody chose");
  }
});

test("chart series stay distinguishable without colour", () => {
  // Greyscale printing and the commonest forms of colour blindness both reduce a palette to lightness.
  // Series that differ only in hue become one series on paper.
  const src = fs.readFileSync(path.join(scriptsDir, "office", "theme.py"), "utf8");
  const m = /^SERIES = \[([^\]]+)\]/m.exec(src);
  assert.ok(m, "SERIES is defined");
  const hexes = [...m[1].matchAll(/"([0-9A-Fa-f]{6})"|ACCENT/g)].map((x) => x[1] ?? token(src, "ACCENT"));
  assert.ok(hexes.length >= 4, "enough series colours to chart with");
  const lums = hexes.map(luminance).sort((a, b) => a - b);
  for (let i = 1; i < lums.length; i++) {
    assert.ok(lums[i] - lums[i - 1] > 0.008, `series ${i} and ${i - 1} are too close in lightness to tell apart in greyscale`);
  }
});

test("the type scale steps, and nothing in a document is unreadably small", () => {
  const src = fs.readFileSync(path.join(scriptsDir, "office", "theme.py"), "utf8");
  const body = /"body": ([\d.]+)/.exec(src);
  const caption = /"caption": ([\d.]+)/.exec(src);
  const h1 = /"h1": ([\d.]+)/.exec(src);
  assert.ok(body && caption && h1);
  assert.ok(Number(caption[1]) >= 8, "a caption below 8pt is decoration, not information");
  assert.ok(Number(body[1]) >= 10, "body text below 10pt is uncomfortable on paper");
  assert.ok(Number(h1[1]) > Number(body[1]) * 1.4, "a heading has to be obviously a heading");
  // Slides are a different medium: 17pt is the floor there, and the scale must say so.
  assert.match(src, /"body": Pt\(17\)/, "the slide body size is the readable-from-the-back floor");
});

test("all four skills use the shared system rather than inventing their own", () => {
  for (const id of SKILLS) {
    const raw = fs.readFileSync(path.join(skillsMd, `${id}.md`), "utf8");
    assert.match(raw, /\{\{SKILLS_DIR\}\}\/office"\)\s*\nimport theme/, `${id} imports the design system`);
    assert.match(raw, /## Make it look designed/, `${id} states its design rules`);
    assert.match(raw, /Never do these/, `${id} names the anti-patterns, which is what a model needs most`);
  }
});

test("no skill hard-codes a colour the design system owns", () => {
  // A stray hex in a recipe is how four documents stop looking related.
  const stray = [];
  for (const id of SKILLS) {
    const raw = fs.readFileSync(path.join(skillsMd, `${id}.md`), "utf8");
    for (const m of raw.matchAll(/#?\b(?:0x)?([0-9A-F]{6})\b/g)) {
      const hex = m[1];
      // The brand-swap examples are deliberate, and so is a colour named as an anti-pattern.
      if (["7A1E2B", "4472C4"].includes(hex)) continue;
      stray.push(`${id}.md: ${hex}`);
    }
  }
  assert.deepEqual(stray, [], "colours come from theme.py");
});
