/**
 * Generic "renderer → main process" large-data transfer channel (based on MessagePort transfer).
 *
 * Why not ipcRenderer.invoke: invoke serializes arguments wholesale via structured clone, so a
 * large ArrayBuffer gets fully copied into the message in the renderer and copied again when
 * deserialized in the main process; MessagePort instead hands over buffer ownership with transfer
 * semantics (the renderer no longer holds it), backed by Mojo shared memory — more memory-efficient
 * and without tying up the main IPC channel. It suits transferring data that has no host path and
 * whose bytes live only in renderer memory (e.g. synthetic files dragged out of a webview, Blobs
 * generated by a canvas). Real disk files should still pass only a path (see saveAttachment's
 * srcPath branch) and need not move any bytes at all.
 *
 * Protocol (each call uses a one-shot MessageChannel, discarded after use; request/response pair up
 * naturally, so no request id is needed):
 *   Renderer: ipcRenderer.postMessage("transfer:port", { kind, meta }, [port2])  // hand over a port + metadata
 *            port1.postMessage(buffer, [buffer])                                 // transfer the bytes
 *   Main process: route by kind to handler(meta, ArrayBuffer) → result sent back over the same port → close the port
 *
 * Usage (main process, once after app ready):
 *   installTransferBridge();
 *   onTransfer("save-attachment", async (meta, buffer) => { …; return absPath; });
 */
import { ipcMain } from "electron";

const handlers = new Map(); // kind -> async (meta, ArrayBuffer) => value

/** Register a transfer handler. kind is unique (re-registering overwrites); the handler's return value is sent back to the renderer. */
export function onTransfer(kind, handler) {
  handlers.set(kind, handler);
}

let installed = false;

/** Install the IPC receiving end (idempotent; repeat calls have no side effects). */
export function installTransferBridge() {
  if (installed) return;
  installed = true;
  ipcMain.on("transfer:port", (event, envelope) => {
    const port = event.ports?.[0];
    if (!port) return;
    const kind = envelope?.kind;
    const meta = envelope?.meta;
    let done = false; // each port handles only one data message, then closes
    port.on("message", async (e) => {
      if (done) return;
      done = true;
      try {
        const handler = handlers.get(kind);
        if (!handler) throw new Error(`no transfer handler registered for kind: ${kind}`);
        const value = await handler(meta, e.data);
        port.postMessage({ ok: true, value });
      } catch (err) {
        port.postMessage({ ok: false, error: String(err?.message ?? err) });
      } finally {
        port.close();
      }
    });
    port.start();
  });
}
