/**
 * Native tool SCHEMAS — the declarations sent to the model.
 *
 * Split out of aiToolkit.mjs so they can be read without the Electron runtime. aiToolkit imports `shell` for open_path, which made
 * the whole module unloadable outside Electron; the schemas themselves are static data and are needed by the seed tooling, which
 * has to compute the exact prompt prefix without launching an app.
 *
 * Executing a tool still lives in aiToolkit. This file is declarations only.
 */
const READ_DEFAULT_MAX_LINES = 2000; // mirrors aiToolkit's default; schemas are declarations, so this must not import it back
const str = (description) => ({ type: "string", description });
const bool = (description) => ({ type: "boolean", description });
const num = (description) => ({ type: "number", description });

const fn = (name, description, properties, required) => ({
  name,
  description,
  parameters: { type: "object", properties, required },
});

export const TOOLS = [
  fn("read_file",
     `Read the UTF-8 text content of a file. Small files come back whole. For a large file, read the slice you actually need via offset/limit instead of pulling in the entire file — use search_in_files first to find the line you want, then read around it. The result says which lines you got and whether more remain (up to ${READ_DEFAULT_MAX_LINES} lines per call by default).`,
     { path: str("File path."),
       offset: num("First line to read, 1-based. Defaults to 1 (start of file)."),
       limit: num(`How many lines to read from offset. Defaults to ${READ_DEFAULT_MAX_LINES}.`) },
     ["path"]),
  fn("open_path",
     "Open a file or folder in the host's DEFAULT APPLICATION for the user to see (view an image, play a video/audio, open a document/PDF, reveal a folder). This runs on the host machine. Use THIS — not run_command — to open/show/play a file: run_command may be running inside an isolated headless Linux sandbox with no GUI, so it cannot launch the user's apps. Path is resolved inside the working directory.",
     { path: str("Path to the file or folder to open, relative to the working directory.") }, ["path"]),
  fn("write_file", "Write UTF-8 text to a file, overwriting it.",
     { path: str("File path."), content: str("Full text to write.") }, ["path", "content"]),
  fn("edit_file", "Replace a literal string in a file. Without replace_all the match must be unique.",
     { path: str("File path."),
       old_string: str("Exact text to replace (literal, not regex)."),
       new_string: str("Replacement text."),
       replace_all: bool("Replace every occurrence; defaults to false.") },
     ["path", "old_string", "new_string"]),
  fn("append_file", "Append UTF-8 text to a file (creating it if needed).",
     { path: str("File path."), content: str("Text to append.") }, ["path", "content"]),
  fn("delete_file", "Delete a file.",
     { path: str("File path.") }, ["path"]),
  fn("copy_file", "Copy a file to a new path (overwrites the destination).",
     { source: str("Source path."), destination: str("Destination path.") }, ["source", "destination"]),
  fn("move_file", "Move or rename a file (overwrites the destination).",
     { source: str("Source path."), destination: str("Destination path.") }, ["source", "destination"]),
  fn("file_info", "Get metadata for a file or directory (size, type, modified time).",
     { path: str("Path to inspect.") }, ["path"]),
  fn("list_directory", "List the entries of a directory (defaults to the working directory).",
     { path: str("Directory path; optional.") }, []),
  fn("create_directory", "Create a directory (including parents).",
     { path: str("Directory path to create.") }, ["path"]),
  fn("search_files", "Find files by name using a glob pattern, recursively.",
     { pattern: str("Glob, e.g. *.txt or report*.md.") }, ["pattern"]),
  fn("search_in_files",
     "Search file contents recursively and return each match WITH surrounding context lines, so you usually don't need to open the file afterward. Prefer ONE precise search (use regex / a filename pattern) over many broad ones.",
     { query: str("Text or regular expression to search for."),
       pattern: str("Optional filename glob to scope the search, e.g. *.md or *.{ts,tsx}."),
       regex: bool("Treat query as a JavaScript regular expression; defaults to false (plain substring)."),
       ignore_case: bool("Case-insensitive match; defaults to false."),
       context: num("Context lines to show around each match (0–5, default 2).") },
     ["query"]),
  fn("run_command",
     "Run a shell command in the working directory and return its output. For long-running / persistent processes (dev servers, watchers, `npm run dev`, `pnpm start`, vite/webpack/nodemon, etc.) pass background:true so it keeps running instead of being killed at the 60s timeout — the tool returns early with the startup output (including any http://localhost:PORT). (Such commands are also auto-detected as background.) Starting a dev server is not a reason to open a browser: report the URL to the user, and only open it if they asked or the work is finished.",
     { command: str("The shell command line to execute."),
       background: bool("Run as a persistent, non-blocking background process (dev servers / watchers / long-running tasks). Not killed at the timeout."),
       notify: bool("With background:true, have the command report back when it FINISHES, with its output. Use this for slow one-off work that the rest of the task depends on — `npm install`, `pip install`, a big `git clone`, a build — so the user can keep talking to you while it runs and you are woken with the result. Having set it, end your turn: never poll, sleep, re-run, or ask whether it is done. Pointless for a dev server or watcher, which is meant never to finish."),
       sandbox: bool("Run this one command inside the Linux sandbox (Debian, bash) instead of wherever commands normally run, for the document/media toolchain (imagemagick, ffmpeg, librsvg, pandoc, LibreOffice, OCR, python) that is preinstalled there and absent from the host. The working directory is the same — it is mounted in — so outputs are readable by the file tools afterwards. Use it only for that toolchain: builds, tests, git and anything depending on the project's installed dependencies must run normally, on the host.") },
     ["command"]),
  fn("stop_service",
     "Stop a background service (e.g. a dev server) you started earlier via run_command, by its pid (from the start result) or url. ALWAYS use this to stop such services — NEVER use taskkill/kill/pkill on node/electron or the app itself, which would kill this application or unrelated processes.",
     { pid: num("The pid of the background service to stop (from the run_command start result)."),
       url: str("Alternatively the service URL, e.g. http://localhost:8081.") }, []),
  fn("check_project",
     "Compile and test the project, auto-detecting its type (Node/TS → tsc/lint/test, Rust → cargo check/test, Go → go build/test, Python → compileall/pytest). Call this after modifying code to verify it still builds and passes; fix any reported failures.",
     { skip_tests: bool("Only run compilation / type-check, skip tests; defaults to false.") }, []),
  fn("refine_question",
     "Refine a vague or colloquial question into a clear, specific, self-contained one that is easier to search and answer. Returns only the refined question, in the same language as the input.",
     { question: str("The original (possibly vague) question to refine."),
       context: str("Optional surrounding conversation/context to clarify intent; not answered, only used to understand the question.") },
     ["question"]),
  fn("init_command",
     "Initialize or refresh project memory: bring ZERAIX.md at the working-directory root up to date and return it — a structured map of the project (repo type, tech stack, key config files, directory structure, scripts, README) that later turns read instead of rescanning the repo. Use this when the user asks to initialize / analyze / understand the project, explain the codebase, or 'what's in this folder'. Cheap to call repeatedly: it only rebuilds the sections whose underlying files actually changed, and writes nothing when the project is unchanged, so call it at the start of a task rather than assuming an existing ZERAIX.md is current. Sections a human has written or frozen are never overwritten. Pass refresh:true to force every generated section to be rebuilt. Only reads config/text files (never binaries) and skips node_modules/.git/dist/build/coverage/.next etc.",
     { refresh: bool("Rebuild every generated section even if its inputs are unchanged; defaults to false, which rebuilds only what went stale.") },
     []),
  fn("remember_project",
     "Record something you learned about THIS project into its long-term memory (ZERAIX.md), so future sessions start knowing it instead of rediscovering it. Call this whenever you worked something out that the project map does not already state — especially right after reading code or running a sub-agent to answer a question about how part of the codebase works, and whenever the user explains a convention, constraint or gotcha ('we use npm here, not pnpm', 'never touch fs from the renderer'). Two uses: pass `module` plus a one-sentence `note` to replace that module's line in the Module Map with a description based on what you actually read (this pins the line so it is never regenerated); or pass `note` alone to append a durable fact to the project's Invariants & Gotchas section. Keep each note to one specific, self-contained sentence, and record only things that will still be true next week — not what you are doing right now.",
     { note: str("One clear sentence. As a module description: what that directory is responsible for and its entry point. As a standalone note: an invariant, convention, constraint or gotcha worth knowing before touching this project."),
       module: str("Optional module path exactly as it appears in the Module Map, e.g. 'electron' or 'src/lib'. Omit to append a general note instead.") },
     ["note"]),
  fn("web_search",
     "Search the web and get ranked results (title, URL, snippet) back as text, directly — WITHOUT opening the visible browser panel. This is your built-in, fastest way to look things up online: current events, facts that may have changed since training, documentation, library/API usage, exact error messages, product/price info, etc. Prefer web_search over openBrowser for information lookups. Typical flow: web_search to find sources → fetch_url on the most relevant result to read it → answer and cite the URL. Do NOT answer from memory when the user asks about anything current, niche, or verifiable; search first. Only use openBrowser instead when the user needs to visually SEE a page, or the page requires interaction / login / JavaScript.",
     { query: str("The search query. Prefer concise, keyword-style queries; for precise lookups include distinctive terms (exact error text, proper names, version numbers). Use the user's language unless an English query would find better sources."),
       count: num("Number of results to return (1–10, default 6). Ask for more only when you need to compare several sources.") },
     ["query"]),
  fn("fetch_url",
     "Fetch a single web page or HTTP(S) API by URL and return its main readable text (HTML is stripped to text; JSON / plain text is returned as-is) — headless, without opening the visible browser. Use it to read a specific result from web_search, or any URL you already know (docs page, raw file, JSON API). It does NOT execute JavaScript and cannot log in, click, or fill forms; for pages that need rendering / interaction, or that the user should see on screen, use openBrowser + browser instead. Long pages are truncated, so target the specific page you need rather than large index pages.",
     { url: str("Absolute http(s) URL to fetch.") },
     ["url"]),
  fn("page_console",
     "Load a web page HEADLESSLY — JavaScript runs — and get back what the page itself logged: console.* output, uncaught exceptions, unhandled promise rejections, failed requests and load failures. No visible browser opens and openBrowser is NOT involved, so this costs the user nothing to watch. THIS is how you check whether a page actually works after you changed it: start the dev server with run_command(background: true), then call this on the URL it printed. A page can compile cleanly, pass check_project, render in a screenshot and still be throwing on every load — the console is the only place that shows it, and it is the first thing you should look at when the user reports that something 'doesn't work' in a web page, is blank, or fails in the browser. Also takes a path inside the working directory, to load a local .html file. It only loads the page and waits: it cannot click, type, log in, or reach output that appears only after an interaction — use openBrowser + browser for that, and only when the user asked for a browser.",
     { url: str("Absolute http(s) URL to load (e.g. the dev-server URL run_command printed), or a path to an .html file inside the working directory."),
       wait_ms: num("How long to keep the page open after it loads, so client-side code can run and throw, in milliseconds (default 2500, max 15000). Raise it for a slow app that fetches on mount."),
       level: str("Minimum severity to return: 'error', 'warn', or 'all' (default 'all'). Use 'error' when you only care whether the page is broken."),
       max: num("Maximum number of messages to return (default 50); the most recent are kept.") },
     ["url"]),
  fn("mcp_tools",
     "List the tools that the user's CONNECTED MCP servers expose, and get their parameter schemas. These tools are deliberately not in your tool list — this call is how you reach them, and they are then invoked through `call_tool`. Connected servers are integrations the user has already set up: their own GitHub or Notion account, a database, a browser, a desktop application such as Blender. Call this BEFORE telling the user that something is outside your abilities, and whenever a task mentions a specific external service, application or data source — the capability you need may already be connected, and you have no other way to find out. Call it with no arguments for the inventory (server names, tool names, one-line descriptions), then again with `name` or `server` to get the parameter schemas you need in order to actually make a call. Read-only: it never connects, changes or runs anything. If nothing is connected and the user wants an integration, use mcp_discover instead.",
     { name: str("Full name of one tool, e.g. 'mcp__github__create_issue', to get just that tool's parameter schema."),
       server: str("A connected server's id, e.g. 'github', to get parameter schemas for all of its tools.") },
     []),
  fn("plugin_tools",
     "List the tools that the user's INSTALLED PLUGINS expose, and get their parameter schemas. Plugins are integrations the user installed from the Zeraix marketplace and connected to their own account — a plugin for Gmail carries that account's real mailbox, one for Figma their real files. Like MCP tools these are deliberately not in your tool list: this call is how you reach them, and they are then invoked through `call_tool`. Call it BEFORE telling the user something is outside your abilities, and whenever a task names a service the user might have installed a plugin for — a connected plugin is usually the most direct and most trustworthy route to that service, since the credential is the user's own and scoped to what they approved. Call with no arguments for the inventory (plugin, tool names, one-line descriptions), then again with `name` or `plugin` for the parameter schemas you need. Read-only: it installs, connects and changes nothing. If the tool you need is missing, the plugin may be installed but not connected — say so rather than guessing; the user connects it on the Plugins page.",
     { name: str("Full name of one tool, e.g. 'plugin__zeraix_gmail__users_messages_send', to get just that tool's parameter schema."),
       plugin: str("A plugin id, e.g. 'zeraix/gmail', to get parameter schemas for all of its tools.") },
     []),
  fn("sandbox_tools",
     "List what is installed in the Linux sandbox — language runtimes with their exact versions, and the document / image / media toolchain — plus how to run any of it. The sandbox is a Debian VM carrying things the user's machine does not have: Python, Node.js and a JDK for running and compiling code, and imagemagick, ffmpeg, librsvg, pngquant, graphviz, poppler, ghostscript, LibreOffice, pandoc, offline OCR, pymupdf4llm / pdfplumber / python-docx / openpyxl / Pillow for files. Call this WHENEVER you are about to run or compile code in Python, JavaScript/Node or Java, whenever the user asks you to work with an image, photo, screenshot, icon, SVG, chart, diagram, audio, video, PDF or Office file, and ALWAYS before saying you cannot run something or cannot edit or convert a file. The reply is probed from the running sandbox, so the tools and version numbers are what is genuinely there rather than an assumption, and it explains how to run them from wherever your commands currently execute — including when they default to the host. Read-only; it installs and changes nothing.",
     { query: str("Optional filter to narrow the list to one job, e.g. 'pdf', 'image', 'video', 'ocr', 'excel'. Omit for the full inventory.") },
     []),
  fn("mcp_discover",
     "Find MCP servers the user could connect to, and list the ones they already have. MCP servers add whole new capability sets to you: a web service's own API (GitHub, Notion), a database, a browser — and DESKTOP APPLICATIONS RUNNING ON THIS MACHINE, such as Blender for 3D modelling or Ableton for music, which you can then operate directly on the user's behalf. Call this whenever the user asks to connect / add / set up an MCP server or integration, asks whether you can drive or work with some application or service, or asks what MCP servers they have — INCLUDING when they only name the target ('can you connect to my GitHub?', 'can you model something in Blender?'), because they usually do not know the package name or command line and this is what finds it. Searches a built-in list of common servers plus the official public MCP registry, and returns ready-to-use configurations, anything the user must still supply (an API key, a directory path), and any setup needed inside the application itself. Read-only: it never installs, connects, or changes anything. ALWAYS follow it by putting the results to the user with ask_user and letting them choose — never pick a server for them.",
     { query: str("What the user wants the server for, in plain words — a service or application name ('github', 'notion', 'blender'), or a capability ('browser automation', '3d modelling', 'read my postgres database'). Omit to just list common servers and what is already configured.") },
     []),
  fn("mcp_connect",
     "Connect the MCP server the user chose, making its tools immediately available to you for the rest of the conversation. Also disconnects or removes one, via `action`. Call this ONLY for a server the user has actually picked — normally the option they selected from the ask_user choices you showed after mcp_discover. Pass the id and configuration exactly as mcp_discover printed them, adding any values the user supplied (API keys as `env` or `headers`, paths as extra `args`). The server is saved, authorised and connected in one step, and reconnects automatically in future sessions, so this both installs and connects. The user confirms the exact command line before it runs. If mcp_discover listed SETUP REQUIRED for this server — the case for one that bridges to a desktop application like Blender or Ableton — do not call this until the user has confirmed the application is open with its MCP add-on connected, or every tool call afterwards will fail. Never invent a package name or command: if mcp_discover found nothing, research the server's real configuration first and say where you got it.",
     { id: str("Short id for this server, e.g. 'github'. Becomes part of its tool names (mcp__github__search). A–Z, a–z, 0–9, '_' and '-' only. Reuse the exact id of an already-configured server to reconnect or change it."),
       action: str("'connect' (default) to configure and connect; 'disconnect' to stop it but keep the configuration; 'remove' to delete it entirely."),
       command: str("For a local server: the program to run, e.g. 'npx', 'uvx', 'docker'. Give this OR url, never both."),
       args: { type: "array", items: { type: "string" }, description: "Arguments for `command`, in order, e.g. ['-y', '@playwright/mcp@latest']. Include any path or option the user supplied." },
       env: { type: "object", additionalProperties: { type: "string" }, description: "Environment variables for a local server, e.g. { \"GITHUB_TOKEN\": \"ghp_...\" }. This is where an API key goes. Stored in the app's MCP config; never echo the value back to the user." },
       cwd: str("Optional working directory for a local server."),
       url: str("For a hosted server: its Streamable HTTP endpoint, e.g. 'https://mcp.example.com/mcp'. Give this OR command, never both."),
       headers: { type: "object", additionalProperties: { type: "string" }, description: "HTTP headers for a hosted server, e.g. { \"Authorization\": \"Bearer sk-...\" }. This is where a hosted server's token goes." },
       timeoutMs: num("Optional per-call timeout in milliseconds; defaults to 60000. Raise it only for a server known to be slow.") },
     ["id"]),
];
