/**
 * Loader for the skin-engine addon.
 *
 * Written by hand rather than generated by @napi-rs/cli: the CLI is a devDependency this repo does
 * not carry (see docs/theming-feature-prompt-set-v2-rust-en.md, Stage 0), and the generated file is
 * ten lines of platform switch. The binary beside this file is produced by
 * scripts/build-skin-engine.mjs, named `skin-engine.<platform>-<arch>[-<abi>].node` the way napi-rs
 * names its own artefacts, so a prebuilt from either toolchain drops in unchanged.
 *
 * Inside the packaged app the .node lives in app.asar.unpacked (electron-builder.yml asarUnpack);
 * Electron redirects `require` of an unpacked file there on its own.
 */
"use strict";

const { platform, arch } = process;

const TRIPLES = {
  "win32-x64": "win32-x64-msvc",
  "win32-arm64": "win32-arm64-msvc",
  "darwin-arm64": "darwin-arm64",
  "darwin-x64": "darwin-x64",
  "linux-x64": "linux-x64-gnu",
  "linux-arm64": "linux-arm64-gnu",
};

const triple = TRIPLES[`${platform}-${arch}`];
if (!triple) {
  throw new Error(`skin-engine: no binary for ${platform}-${arch}`);
}

module.exports = require(`./skin-engine.${triple}.node`);
