import { Boxes, Brain, Info, KeyRound, SlidersHorizontal, User, Volume2 } from "lucide-react";


export type SectionId = "account" | "models" | "keys" | "memory" | "general" | "notify" | "about";

export const NAV: { id: SectionId; labelKey: string; icon: typeof User }[] = [
  { id: "account", labelKey: "settings.account", icon: User },
  { id: "models", labelKey: "settings.models", icon: Boxes },
  { id: "keys", labelKey: "settings.keys", icon: KeyRound },
  { id: "memory", labelKey: "settings.memory", icon: Brain },
  { id: "notify", labelKey: "settings.notify", icon: Volume2 },
  { id: "general", labelKey: "settings.general", icon: SlidersHorizontal },
  { id: "about", labelKey: "settings.about", icon: Info },
];

/** The i18n keys each section contributes to search (title + description + fields), matched by substring after translation. */
export const SECTION_KEYS: Record<SectionId, string[]> = {
  account: [
    "settings.account",
    "account.info",
    "account.manage",
    "account.privacy",
    "account.privacyDesc",
    "account.logout",
    "account.upgrade",
    "account.upgradeDesc",
    "plan.free",
  ],
  models: [
    "settings.models",
    "models.desc",
    "models.added",
    "models.addOfficial",
    "models.addCustom",
    "models.provider",
    "models.model",
    "models.default",
    "models.empty",
    "models.apiFormat",
    "models.apiFormatOpenAI",
    "models.apiFormatResponses",
    "models.customUrl",
    "models.fullUrl",
    "models.modelId",
    "models.multimodal",
    "models.apiKey",
    "models.official",
    "models.officialNote",
  ],
  keys: [
    "settings.keys",
    "keys.desc",
    "keys.empty",
    "keys.forProvider",
    "keys.placeholder",
    "keys.official",
    "keys.officialDesc",
    "keys.localTitle",
    "keys.generate",
    "keys.regenerate",
  ],
  memory: [
    "settings.memory",
    "memory.desc",
    "memory.items",
    "memory.empty",
    "memory.openDir",
    "memory.create",
    "memory.import",
    "memory.template",
    "memory.export",
    "projmem.title",
    "projmem.desc",
    "projmem.rebuild",
  ],
  general: [
    "settings.general",
    "general.storage",
    "general.storageDesc",
    "general.migrateNote",
    "general.appConfig",
    "general.appConfigDesc",
    "general.appConfigOpen",
    "general.background",
    "general.backgroundDesc",
    "general.backgroundEnable",
    "general.backgroundAutostart",
  ],
  notify: [
    "settings.notify",
    "notify.desc",
    "notify.roundComplete",
    "notify.roundCompleteDesc",
    "notify.mode.never",
    "notify.mode.unfocused",
    "notify.mode.always",
    "notify.permission",
    "notify.permissionDesc",
    "notify.question",
    "notify.questionDesc",
    "notify.remindersTitle",
    "notify.soundsTitle",
    "notify.master",
    "notify.masterDesc",
    "notify.volume",
    "notify.typeInfo",
    "notify.typeSuccess",
    "notify.typeWarning",
    "notify.typeError",
    "notify.preview",
    "notify.upload",
    "notify.custom",
    "notify.builtin",
    "notify.reset",
    "notify.unsupported",
  ],
  about: [
    "settings.about",
    "about.title",
    "about.desc",
    "about.version",
    "about.updates",
    "about.check",
    "about.upToDate",
    "about.unsupported",
    "about.links",
    "about.github",
    "about.githubDesc",
  ],
};

/** Normalized substring matcher: an empty query always matches. */
export function makeMatcher(query: string) {
  const q = query.trim().toLowerCase();
  return (...texts: string[]) => q === "" || texts.some((t) => t.toLowerCase().includes(q));
}
