/**
 * The curated icon set a skin's Icon primitive may draw from, keyed by lucide's kebab-case names.
 *
 * Each icon is imported by name on purpose: importing lucide's `icons` map would pull the whole set
 * (well over a thousand SVGs) into the renderer bundle. The record is typed against ICON_NAMES from
 * schemas.ts, so adding a name there without a component here (or the reverse) fails to compile.
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity, Anchor, ArrowRight, Battery, BatteryCharging, Bell, Bike, Bird, Bluetooth, Bookmark, Bot,
  Brain, Calendar, Camera, Car, Cat, ChartBar, ChartPie, Check, CircleQuestionMark, Clock, Cloud,
  CloudSun, Code, Coffee, Compass, Cpu, Dog, Download, Droplet, ExternalLink, FileText, Fish, Flag,
  Flame, Flower, Flower2, Folder, Gamepad2, Ghost, Gift, Globe, Grid3x3, Headphones, Heart, House,
  Image, Info, Key, Layers, Leaf, Lightbulb, Link, Loader, Lock, Mail, MapPin, MessageSquare, Mic,
  Moon, MoonStar, Mountain, Music, Palette, Phone, Plane, Plus, RefreshCw, Rocket, Search, Settings,
  Shield, Smile, Snowflake, Sparkles, Star, Sun, SunMoon, Tag, Terminal, Thermometer, Trees,
  TrendingUp, TriangleAlert, Trophy, Umbrella, Upload, User, Users, Video, Volume2, WandSparkles,
  Waves, Wifi, Wind, X, Zap,
} from "lucide-react";
import { ICON_NAMES, type IconName } from "./schemas";

export { ICON_NAMES };
export type { IconName };

export const ICONS: Readonly<Record<IconName, LucideIcon>> = Object.freeze({
  sun: Sun,
  moon: Moon,
  "sun-moon": SunMoon,
  "moon-star": MoonStar,
  zap: Zap,
  battery: Battery,
  "battery-charging": BatteryCharging,
  cloud: Cloud,
  "cloud-sun": CloudSun,
  sparkles: Sparkles,
  heart: Heart,
  star: Star,
  leaf: Leaf,
  snowflake: Snowflake,
  flame: Flame,
  droplet: Droplet,
  wind: Wind,
  umbrella: Umbrella,
  thermometer: Thermometer,
  bot: Bot,
  brain: Brain,
  "message-square": MessageSquare,
  folder: Folder,
  "file-text": FileText,
  check: Check,
  x: X,
  plus: Plus,
  "arrow-right": ArrowRight,
  calendar: Calendar,
  clock: Clock,
  settings: Settings,
  user: User,
  users: Users,
  house: House,
  search: Search,
  bell: Bell,
  shield: Shield,
  lock: Lock,
  key: Key,
  globe: Globe,
  "map-pin": MapPin,
  compass: Compass,
  image: Image,
  music: Music,
  coffee: Coffee,
  gift: Gift,
  rocket: Rocket,
  trophy: Trophy,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  layers: Layers,
  "grid-3x3": Grid3x3,
  cpu: Cpu,
  terminal: Terminal,
  code: Code,
  "wand-sparkles": WandSparkles,
  palette: Palette,
  activity: Activity,
  "trending-up": TrendingUp,
  "chart-pie": ChartPie,
  "chart-bar": ChartBar,
  smile: Smile,
  ghost: Ghost,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  flower: Flower,
  "flower-2": Flower2,
  trees: Trees,
  mountain: Mountain,
  waves: Waves,
  anchor: Anchor,
  plane: Plane,
  car: Car,
  bike: Bike,
  "gamepad-2": Gamepad2,
  headphones: Headphones,
  camera: Camera,
  mic: Mic,
  video: Video,
  lightbulb: Lightbulb,
  mail: Mail,
  phone: Phone,
  link: Link,
  "external-link": ExternalLink,
  download: Download,
  upload: Upload,
  "refresh-cw": RefreshCw,
  loader: Loader,
  info: Info,
  "triangle-alert": TriangleAlert,
  "circle-question-mark": CircleQuestionMark,
  wifi: Wifi,
  bluetooth: Bluetooth,
  "volume-2": Volume2,
});
