/**
 * Resident KV seeds: download and install.
 *
 * A seed is pre-computed KV for the `[messages[0] + tools]` prefix. With one installed, a user's FIRST request skips prefilling
 * that whole region — measured at 99.8% of 9,619 tokens served from the seed. Generated by scripts/gen-seed.mjs, published beside
 * the llama-server build, unpacked here into `<kvDiskDir>/<model_key>/` where llama-server's startup scan finds it.
 *
 * Everything here fails soft. A seed is an optimisation: if the download 404s, the disk is full, or the archive is corrupt, the app
 * must still run — just with a cold first prefill. Nothing in this file may throw into the launch path.
 */
import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import http from "node:http";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import { kvTypeName } from "./localModels.mjs";

/**
 * Seeds ship from a HuggingFace repo, not GitHub releases and not the CDN that serves the pinned upstream build.
 *
 * HF rather than GitHub for three reasons, in increasing order of importance. Size: an asset is 100-300 MB per model and a full set
 * is ~700 MB, which GitHub tolerates per file but adds up badly across releases — and a new set is published every time the prompt
 * changes, not every time the binary does. Purpose: HF is built for exactly this, large versioned binary artifacts over git-lfs.
 * And decisively, China reachability: the app already falls back to hf-mirror.com when huggingface.co is unreachable (see
 * hfDownload.mjs), which the CN edition depends on. GitHub has no equivalent, so seeds published there would simply not arrive for
 * a chunk of users.
 *
 * Layout is a plain directory per seed key — no releases, no git tags; an HF repo is a git repo and the key is just a path:
 *
 *   <prefixHash>-r<revision[0:8]>-kvd<KVD_VER>-<kvType>/seed-<modelId>-<mode>-<prefixHash>.tar.gz
 *
 * Three of the four identity components are in that path, so a mismatch is a 404 before any bytes move. The fourth, model_key, is
 * the directory name INSIDE the archive — the app cannot know it in advance (the server derives it at startup, after the download
 * had to happen), and unpacking files it exactly where the server looks.
 *
 * macOS only: the KV disk tier exists only in the fork's build and only the mac build is published. Windows keeps the stock
 * upstream binary and none of this runs there.
 */
const SEED_REPO = process.env.ZERAIX_SEED_REPO || "Zeraix/llama-seeds";

/**
 * Seed URL, on the SAME HF host the model weights came from.
 *
 * The endpoint is passed in rather than hardcoded: localServer probes huggingface.co once and falls back to hf-mirror.com when it
 * is unreachable, which is what the CN edition depends on. Choosing HF over GitHub for seeds was justified by that fallback, so
 * the seed download has to actually use it — hardcoding huggingface.co here would have left exactly the users the argument was
 * about unable to fetch anything.
 */
const seedUrl = (endpoint, key, asset) =>
  `${(process.env.ZERAIX_SEED_BASE || `${endpoint}/${SEED_REPO}/resolve/main`).replace(/\/+$/, "")}/${key}/${asset}`;

/**
 * Seed identity, and why it is keyed this way.
 *
 * `prefixHash` covers the exact bytes of the prompt + tool declarations, so any change to either invalidates the seed with nobody
 * having to remember to bump a version. It deliberately does NOT cover the chat template — that lives in the GGUF and can change
 * under a fixed model id, which is what `revision` pins. And `model_key` is the server's own content-address of the KV layout: a
 * seed built for different KV quantisation or geometry must never be loaded, and the per-model sub-folder is what enforces that.
 */
export function seedAssetName(modelId, mode, prefixHash) {
  return `seed-${modelId}-${mode}-${prefixHash}.tar.gz`;
}

/**
 * The seed key: the repo path a seed lives under, and the name of the marker recording it as installed.
 *
 * `<prefixHash>-r<revision8>-kvd<N>-<kvType>`. Every component is something that, if it differs, makes the seed unusable — so a
 * mismatch is a 404 before any bytes move rather than a download that silently never borrows.
 *
 * `kvType` is here because the server mixes the KV cache types into the model_key it files units under: a seed built at q4_0 is
 * invisible to a server running at q8_0. Without it, publishing a second quantisation would overwrite the first at the same URL.
 *
 * ONE definition, called by the generator, the downloader and the sweeper alike. Four hand-written copies of this template is
 * what let the KV quantisation go missing from it in the first place.
 */
export const seedKey = ({ prefixHash, revision, kvdVersion, kvBits }) =>
  `${prefixHash}-r${String(revision).slice(0, 8)}-kvd${kvdVersion}-${kvTypeName(Number(kvBits))}`;

/** Where a seed for this model would live once installed. */
export function seedInstallDir(kvDiskDir, modelKey) {
  return path.join(kvDiskDir, String(modelKey));
}

/**
 * Size of a seed archive, without downloading it.
 *
 * Needed before the progress bar starts: the model and its seeds are one wait from the user's point of view, so the bar has to be
 * weighted by total bytes rather than running 0-100 twice. Returns 0 on any failure — an unknown size just means that seed does
 * not contribute to the estimate, which is better than blocking the download to find out.
 */
export async function seedSize({ endpoint = "https://huggingface.co", modelId, mode, prefixHash, revision, kvdVersion, kvBits }) {
  if (!modelId || !mode || !prefixHash || !revision || !kvdVersion || !kvBits) return 0;
  const key = seedKey({ prefixHash, revision, kvdVersion, kvBits });
  const url = seedUrl(endpoint, key, seedAssetName(modelId, mode, prefixHash));
  try {
    const res = await fetch(url, { method: "HEAD", redirect: "follow" });
    return res.ok ? Number(res.headers.get("content-length") || 0) : 0;
  } catch {
    return 0;
  }
}

/**
 * Marker recording which seed release is installed.
 *
 * Needed because the app cannot ask "is the seed present?" directly: that would mean knowing model_key, which the SERVER derives
 * from KV geometry at startup and does not exist before launch. The archive's own inner directory IS the model_key, so unpacking
 * into kvDiskDir files it correctly without the app ever computing it — but then nothing on disk says which prefix it came from.
 * Hence a marker per (model, prefix).
 */
const marker = (kvDiskDir, modelId, prefixHash) => path.join(kvDiskDir, `.seed-${modelId}-${prefixHash}`);

export function seedInstalled(kvDiskDir, modelId, prefixHash) {
  try {
    return fs.existsSync(marker(kvDiskDir, modelId, prefixHash));
  } catch {
    return false;
  }
}

/**
 * Fetch with resume, mirroring how model weights are downloaded.
 *
 * A seed is 100-350 MB, so a pause or a dropped connection must not throw the bytes away. The partial lands in `<dest>.part` and a
 * retry sends `Range: bytes=<have>-`, exactly as hfDownload does for weights. Crucially the .part lives beside the final file
 * rather than in a mkdtemp directory — an earlier version staged everything under a temp dir it deleted on any failure, which
 * made every interrupted download restart from zero.
 *
 * `onProgress` reports 0-100 over the WHOLE file including what was already on disk, so resuming at 60% shows 60, not 0.
 */
const get = (url, dest, onProgress = null, signal = null) =>
  new Promise((resolve, reject) => {
    if (signal?.aborted) return reject(new Error("aborted"));
    const part = `${dest}.part`;
    let have = 0;
    try { have = fs.statSync(part).size; } catch { /* no partial yet */ }

    const headers = have > 0 ? { Range: `bytes=${have}-` } : {};
    const req = (url.startsWith("http://") ? http : https).get(url, { timeout: 60000, headers }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        return get(res.headers.location, dest, onProgress, signal).then(resolve, reject);
      }
      // 206 = the server honoured the range; 200 with a range request means it ignored it, so start over rather than append
      // into the middle of a file and produce a corrupt archive.
      const resuming = res.statusCode === 206;
      if (res.statusCode !== 200 && !resuming) {
        res.resume();
        // 416 means the .part is already >= the object: it is stale or complete, so drop it and let the caller retry clean.
        if (res.statusCode === 416) { try { fs.rmSync(part, { force: true }); } catch { /* ignore */ } }
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      if (!resuming) have = 0;

      const total = have + Number(res.headers["content-length"] || 0);
      let got = have, last = -1;
      if (onProgress) {
        res.on("data", (c) => {
          got += c.length;
          const pct = total ? Math.floor((got / total) * 100) : 0;
          if (pct !== last) { last = pct; onProgress(pct); }
        });
      }
      const out = fs.createWriteStream(part, resuming ? { flags: "a" } : { flags: "w" });
      // Stop cleanly on abort: end the stream so the bytes already written are flushed into the .part, then reject. The partial
      // stays on disk, so resuming after a pause continues from where it stopped instead of starting over.
      const onAbort = () => { try { req.destroy(); } catch { /* ignore */ } out.end(() => reject(new Error("aborted"))); };
      signal?.addEventListener("abort", onAbort, { once: true });
      out.on("close", () => signal?.removeEventListener("abort", onAbort));
      res.pipe(out);
      out.on("finish", () =>
        out.close(() => {
          // Only promote once the bytes are all there; a truncated .part must stay a .part so the next run resumes it.
          if (total && fs.statSync(part).size !== total) return reject(new Error("short read"));
          try { fs.renameSync(part, dest); resolve(); } catch (e) { reject(e); }
        }),
      );
      out.on("error", reject);
    });
    req.on("error", reject);
    req.on("timeout", () => req.destroy(new Error("timeout")));
  });

const sha256 = (file) =>
  new Promise((resolve, reject) => {
    const h = crypto.createHash("sha256");
    fs.createReadStream(file).on("data", (d) => h.update(d)).on("end", () => resolve(h.digest("hex"))).on("error", reject);
  });

/**
 * Download and install the seed for one model, if one is published and not already present.
 *
 * Returns a short status string for the launch log. Never throws.
 *
 * Installed by unpacking into a temp dir and renaming into place, so an interrupted download can never leave a half-written seed
 * that the startup scan would then try to preload.
 */
export async function ensureSeed({ kvDiskDir, endpoint = "https://huggingface.co", modelId, mode, prefixHash, revision, kvdVersion, kvBits, onLog = () => {}, onProgress = null, signal = null }) {
  if (!kvDiskDir || !modelId || !mode || !prefixHash || !revision || !kvdVersion || !kvBits) return "skipped (missing key)";
  // A plain directory in the repo, not a git tag or a release — HF repos are git repos with paths, so the seed key IS the folder.
  const key = seedKey({ prefixHash, revision, kvdVersion, kvBits });
  if (seedInstalled(kvDiskDir, `${modelId}-${mode}`, key)) return "already installed";

  const asset = seedAssetName(modelId, mode, prefixHash);
  const url = seedUrl(endpoint, key, asset);
  // Staged under the KV dir, NOT a temp dir: the whole point of resuming is that a partial survives, and a mkdtemp path is both
  // deleted on failure and swept by the OS. `cleanup` therefore removes only the unpacked staging and the completed archive —
  // never the .part, which is what a retry resumes from.
  const inbox = path.join(kvDiskDir, ".incoming");
  fs.mkdirSync(inbox, { recursive: true });
  const tar = path.join(inbox, asset);
  const stage = path.join(inbox, `${asset}.x`);
  const cleanup = () => {
    try { fs.rmSync(stage, { recursive: true, force: true }); } catch { /* ignore */ }
    try { fs.rmSync(tar, { force: true }); } catch { /* ignore */ }
    try { fs.rmSync(`${tar}.sha256`, { force: true }); } catch { /* ignore */ }
  };

  try {
    onLog(`[seed] fetching ${asset}\n`);
    await get(url, tar, onProgress, signal);

    // Optional checksum beside the asset; absent is not fatal, mismatched is.
    try {
      const sumFile = `${tar}.sha256`;
      await get(`${url}.sha256`, sumFile);
      const want = fs.readFileSync(sumFile, "utf8").trim().split(/\s+/)[0];
      const got = await sha256(tar);
      if (want && want !== got) { cleanup(); return `checksum mismatch (${got.slice(0, 12)} != ${want.slice(0, 12)})`; }
    } catch { /* no checksum published — proceed */ }

    fs.rmSync(stage, { recursive: true, force: true });
    fs.mkdirSync(stage, { recursive: true });
    const r = spawnSync("tar", ["-xzf", tar, "-C", stage], { encoding: "utf8", timeout: 120000 });
    if (r.status !== 0) { cleanup(); return `unpack failed: ${(r.stderr || "").slice(0, 120)}`; }

    // The archive contains exactly one directory, named for the model_key it was generated against. Unpacking it into kvDiskDir
    // therefore files it exactly where the server will look — and a seed built for different KV geometry lands under a different
    // key, so the server simply never sees it rather than loading something wrong.
    const inner = fs.readdirSync(stage);
    if (inner.length !== 1 || !/^\d+$/.test(inner[0])) {
      cleanup();
      return `unexpected archive layout (${inner.join(",") || "empty"})`;
    }

    fs.mkdirSync(kvDiskDir, { recursive: true });
    const dest = seedInstallDir(kvDiskDir, inner[0]);
    if (fs.existsSync(dest)) {
      // The server already created its own folder for this key. Move the seed files in beside whatever is there rather than
      // replacing it — an existing conversation's spilled units are still valid and must not be deleted.
      for (const f of fs.readdirSync(path.join(stage, inner[0]))) {
        fs.copyFileSync(path.join(stage, inner[0], f), path.join(dest, f));
      }
    } else {
      fs.renameSync(path.join(stage, inner[0]), dest);
    }
    fs.writeFileSync(marker(kvDiskDir, `${modelId}-${mode}`, key), `${inner[0]}\n`);
    cleanup();
    return `installed ${inner[0]} (${fs.readdirSync(dest).length} files)`;
  } catch (e) {
    // An abort is not a failure: keep the .part so the next attempt resumes, and say so rather than reporting it as unavailable.
    if (signal?.aborted || /aborted/i.test(e?.message ?? "")) {
      try { fs.rmSync(stage, { recursive: true, force: true }); } catch { /* ignore */ }
      return "paused (partial kept)";
    }
    cleanup();
    // 404 is the normal case for a model with no published seed yet, so it is logged plainly rather than as an error.
    return `unavailable (${e?.message ?? e})`;
  }
}
