/**
 * LLM request proxy IPC: renderer window.llm.chat -> main process forwards it (bypassing CORS).
 */
import { ipcMain } from "electron";
import { llmChat, llmChatStream } from "../llm/proxy.mjs";

/** AbortController for each in-flight streaming request, keyed by the stream id generated by the renderer (used by llm:chat:abort to interrupt). */
const llmStreamControllers = new Map();

/** Whether a generation is streaming right now. The hidden-window model release waits for it (main/localModelIdle.mjs). */
export function hasActiveLlmStreams() {
  return llmStreamControllers.size > 0;
}

export function registerLlmProxy() {
  ipcMain.handle("llm:chat", (_e, req) => llmChat(req));
  // Streaming: initiated via invoke, pushes deltas to the originating window via llm:chat:chunk, and resolves on completion (same result structure as llmChat).
  // Interruption goes through llm:chat:abort (one-way send), canceling the corresponding AbortController by id.
  ipcMain.handle("llm:chat:stream", async (e, { id, req }) => {
    const controller = new AbortController();
    llmStreamControllers.set(id, controller);
    try {
      return await llmChatStream(
        req,
        (chunk) => {
          if (!e.sender.isDestroyed()) e.sender.send("llm:chat:chunk", { id, chunk });
        },
        controller.signal,
      );
    } finally {
      llmStreamControllers.delete(id);
    }
  });
  ipcMain.on("llm:chat:abort", (_e, id) => {
    llmStreamControllers.get(id)?.abort();
  });
}
