/**
 * Skill Markdown parsing (shared by the built-in catalog.ts and user uploads).
 *
 * A skill = a Markdown file: YAML frontmatter (wrapped in `---`) metadata + a body of instructions.
 * The frontmatter uses a fixed, simple subset (one line per field): scalars `key: value` and inline
 * arrays `key: [a, b]`, so a tiny parser can read it reliably without pulling in a YAML dependency.
 */
import type { Skill, SkillAudience, SkillScope } from "./types";

type Frontmatter = Record<string, string | string[]>;

/** Parse frontmatter (wrapped in `---`): supports only single-line scalars and single-line inline arrays `[a, b, c]`. Returns { data, body }. */
export function parseFrontmatter(raw: string): { data: Frontmatter; body: string } {
  const m = /^\s*---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw);
  if (!m) return { data: {}, body: raw.trim() };
  const data: Frontmatter = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1];
    const rawVal = kv[2].trim();
    if (rawVal.startsWith("[") && rawVal.endsWith("]")) {
      data[key] = rawVal
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^['"]|['"]$/g, ""))
        .filter(Boolean);
    } else {
      data[key] = rawVal.replace(/^['"]|['"]$/g, "");
    }
  }
  return { data, body: raw.slice(m[0].length).trim() };
}

const str = (v: string | string[] | undefined): string => (typeof v === "string" ? v : "");
const arr = (v: string | string[] | undefined): string[] | undefined =>
  Array.isArray(v) && v.length ? v : undefined;

/** Generate a skill id from text (used as the storage key / load_skill argument): lowercase, whitespace
 *  to hyphens, keep Unicode letters and digits (so a Chinese name isn't wiped out), and strip
 *  leading/trailing hyphens. Used to normalize when the id is missing or non-canonical. */
function slugify(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\p{L}\p{N}_-]+/gu, "")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

/**
 * Parse a skill Markdown into a Skill. Deliberately lenient: many user skills have only name and
 * description, or even no id / body. Therefore:
 *   - missing or non-canonical id → generated by normalizing the name (slugify, supports Chinese names);
 *   - missing name → falls back to the passed-in fallbackName (e.g. the uploaded filename / the
 *     original name being edited);
 *   - missing body → instructions fall back to description (so there is at least some content when
 *     load_skill loads it).
 * Only errors when there is no name, no id, and no fallback, so that no identifier can be derived at all.
 * The error message is a brief English summary; the presentation layer can prepend a localized prefix.
 */
export function skillFromMarkdown(raw: string, fallbackName?: string): Skill {
  const { data, body } = parseFrontmatter(raw);
  const name = str(data.name).trim() || (fallbackName ?? "").trim();
  const id = slugify(str(data.id)) || slugify(name);
  if (!id) throw new Error("a skill needs at least a `name` (or an `id`)");
  const description = str(data.description).trim();
  const audience = str(data.audience);
  const scope = str(data.scope);
  return {
    id,
    name: name || id,
    version: str(data.version) || "1.0.0",
    description,
    author: str(data.author) || undefined,
    tags: arr(data.tags),
    audience: audience === "dev" || audience === "user" ? (audience as SkillAudience) : undefined,
    scope: scope === "general" || scope === "targeted" ? (scope as SkillScope) : undefined,
    allowedTools: arr(data.allowedTools),
    // Fall back to the description when the body is empty, to avoid loading a skill with empty instructions.
    instructions: body.trim() || description,
  };
}
